name:                rearrange
version:             0.1.0.0
github:              "finnbar/rearrange"
license:             BSD3
author:              "Finnbar Keating"
maintainer:          "f.keating@warwick.ac.uk"
copyright:           "2021 Finnbar Keating"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/finnbar/rearrange#readme>

dependencies:
- base >= 4.7 && < 5
- type-level-sets
- effect-monad
- first-class-families

library:
  source-dirs: src
  c-sources: csrc/main.c
  default-extensions:
  - TypeFamilies
  - DataKinds
  - PolyKinds
  - ConstraintKinds
  - GADTs
  - TypeApplications
  - TypeOperators

executables:
  rearrange-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rearrange

tests:
  rearrange-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rearrange
